// <auto-generated />
namespace scrum_and_xp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class db20200421 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(db20200421));
        
        string IMigrationMetadata.Id
        {
            get { return "202004210924309_db20200421"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
