// <auto-generated />
namespace scrum_and_xp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class InfFormPosts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InfFormPosts));
        
        string IMigrationMetadata.Id
        {
            get { return "202004141220393_InfFormPosts"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
